### ISSUE TITLE
Error when Sending 2 messages 4 hours apart

### ISSUE THREAD

**Issue by athenawisdoms** [elastic/elasticsearch-js#1094] opened 2020-02-25 02:42 UTC
I have a Node.js script that runs for 4-5 hours. At the start, a log message is sent to the elasticsearch server (via `winston` logger using `winston-elasticsearch`) and several hours later, a second message is sent just before the program quits.

However, the second send fails with the error

```
(node:16296) UnhandledPromiseRejectionWarning: ResponseError: circuit_breaking_exception
    at IncomingMessage.<anonymous> (/home/athenawisdom/foo/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by delvedor** [comment] 2020-02-25 14:25
Duplicate of https://github.com/elastic/elasticsearch-js/issues/1095.

**Closed by delvedor** 2020-02-25 14:25 UTC
