### ISSUE TITLE
"Error: Unable to parse/serialize body" caused by automatic sniffing with a load balancer

### ISSUE THREAD

**Issue by dlerman** [elastic/elasticsearch-js#218] opened 2015-05-20 06:00 UTC
I was seeing intermittent Serialization errors with the message "Error: Unable to parse/serialize body", which turned out to be caused by automatic sniffing closing connections in midstream.

When automatic sniffing runs, it asks for the current set of nodes, and then calls connectionPool.setHosts with the list of active nodes.  If there are connections in the pool that are no longer active, they are immediately closed.  If someone is in the middle of using one of those connections, the connection can be terminated midstream -- the client gets back half a JSON payload, tries to deserialize it, and throws a Serialization error.

In my case, this was caused by inadvertently using sniffing when the primary host was a load balancer.  The load balancer was happily serving requests, but isn't actually a node itself so gets removed from the pool, and any current requests going through the load balancer fail in this very non-obvious way.

Ideally, connections would be closed in a friendlier way, or at least an easier to debug way.  Barring that, hoping the next person to run into this finds this issue and figures it out and turns off sniffing faster than I did!

**Comment by spalger** [comment] 2015-05-20 14:59
Thanks for debugging this @dlerman, working on replicating in a test and then fixing.

**Comment by trondhindenes** [comment] 2017-02-23 22:41
Did anything happen here? I'm getting the same bug when using nginx in front of Elasticsearch (so Kibana is essentially hitting nginx). The "Discover" tool works fine, but "Visualize" throws this error.

**Comment by spalger** [comment] 2017-02-24 17:38
@trondhindenes Kibana does not use sniffing, so it must be something else.

**Comment by delvedor** [comment] 2019-09-04 14:20
Hello! I'm closing this issue, if the problem is still happening, please fill an issue in the [legacy client repository](https://github.com/elastic/elasticsearch-js-legacy).
Thank you for contributing!

**Closed by delvedor** 2019-09-04 14:20 UTC
Labels: bug, legacy
