### ISSUE TITLE
Why I cannot create child document?

### ISSUE THREAD

**Issue by uf2** [elastic/elasticsearch-js#340] opened 2016-01-14 17:24 UTC
1) I installed the latest version of elasticsearch and command 'curl http://localhost:9200' displays me the following:
```javascript
{
  "name" : "saturn",
  "cluster_name" : "sunsystem",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```
2) Then I created new index and mapping
```javascript
curl -XPUT http://127.0.0.1:9200/index -d '{
    "settings" : {
    "index" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0
    },
    "mappings": {
        "parent": {
            "properties": {     
                "text": {"type": "string"}
            }
        },
        "child": {
            "_parent": {"type": "parent"},
            "properties": {
                "text": {"type": "string"}
            }
        }
    }
}
}'
```
3) Then I created a parent document
```javascript
client.create({
    index: 'index',
    type: 'parent',
    id: '1',
    body: {
        text: 'parent text'
    }
}, function (err, resp) {
    if (err){
        return console.error(err);
    }
    console.log(resp);
});
```
4) Then I tried to create a child document
```javascript
client.create({
    index: 'index',
    type: 'child',
    id: '1',
    parent: '1',
    body: {
        text: 'child text'
    }
}, function (err, resp) {
    if (err){
        return console.error(err);
    }
    console.log(resp);
});
```
... and I got an error:
```javascript
{ error: 
   { root_cause: [ [Object] ],
     type: 'illegal_argument_exception',
     reason: 'Can\'t specify parent if no parent field has been configured' },
  status: 400 }
```
Can anyone explain me what I did wrong?

**Comment by spalger** [comment] 2016-01-14 21:10
I'm not sure what's wrong here.

Closing this since it's not a bug/feature request for the es-js client. I suggest you try asking for help in the [elasticsearch community forums](https://discuss.elastic.co/c/elasticsearch).

**Closed by spalger** 2016-01-14 21:10 UTC
