### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to

### ISSUE THREAD

**Issue by ftayyab** [elastic/elasticsearch-js#1741] opened 2022-08-06 00:57 UTC
## 🐛 Bug Report

Trying to index documents repeatedly inside a loop causing the warning.

## To Reproduce

Paste your code here:

```js
getFiles(basedir).then((files) => {
    const pattern = /(\d\/\d{1,}\/\d{1,})/;
    files.forEach(filepath => {
        fs.readFile(filepath, (err, data )=> {
            let zxy = filepath.match(pattern)[0];
            let base64data = Buffer.from(data).toString('base64');
            /* Possible Memory Leak with elasticsearch library */
            client.index({
                index: 'orders',
                document:{
                    zxy,
                    tile: base64data
                }
            })
        });
    });
});
```

## Expected behavior

Although the documents are indexed, this warning still appears. The warning should not be there.

Paste the results here:

```js

```

## Your Environment

- *node version*: 16.13.1
- `@elastic/elasticsearch` latest
- *os*: Windows
- *any other relevant information*

**Comment by ftejeria** [comment] 2023-04-24 14:22
I removed the warning by adding in the `TransportRequestOptions` for the signal field a `new AbortController().signal;`, here an example `client.search(
    {
    yourQuery
    },
    {
      signal: new AbortController().signal,
    }` Any problem attached to this workaround to remove the warning ?

**Comment by JoshMock** [comment] 2023-04-25 18:53
Closing as a duplicate of https://github.com/elastic/elastic-transport-js/issues/63.

**Closed by JoshMock** 2023-04-25 18:53 UTC
