### ISSUE TITLE
BaseConnectionPool TypeError on 'http' ('publish_address' of undefined)

### ISSUE THREAD

**Issue by rdzar** [elastic/elasticsearch-js#1230] opened 2020-06-22 16:23 UTC
It looks like the property `http` is expected to be present at all times, but isn't there / the requested node prob. returned something different. The code throws the following error, while I expected it to connect with another live node.

```
core/node_modules/es6/lib/pool/BaseConnectionPool.js:194
      var address = node.http.publish_address
                              ^

TypeError: Cannot read property 'publish_address' of undefined
    at ConnectionPool.nodesToHost (core/node_modules/es6/lib/pool/BaseConnectionPool.js:194:31)
    at core/node_modules/es6/lib/Transport.js:367:41
    at f (core/node_modules
```

## To Reproduce
Connect with sniffStart enabled & restart ES 6.8.0 connected server.
ES connection pool will throw error as seen above.

If the machine thats giving as the node, isn't reachable, this error will be throw and sniffing fails. Crashing the node script itself. Previous client lib, you would provide multiple IPs to resolve this issue. I was unable to find a way to provide multiple IPs in the current lib.

## Expected behavior
Auto. recover failed connection
## Your Environment

- *node version*: 12.10.0
- `@elastic/elasticsearch` *version*: ^6.8.7
- *os*: Linux
- *ES*: 6.8.0

## Code part causing the problem
https://github.com/elastic/elasticsearch-js/blob/6.x/lib/pool/BaseConnectionPool.js#L194

Code still lives at master in the same way
https://github.com/elastic/elasticsearch-js/blob/master/lib/pool/BaseConnectionPool.js#L195

**Comment by delvedor** [comment] 2020-06-23 07:18
Hello! I don't understand the steps to reproduce the error, could you expand them a little?
How are you running Elasticsearch? (Docker, executable...)
Is Elasticsearch in the same network as the client?
Does the user have the permissions to use the nodes API?

Providing [multiple nodes](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html#_basic_options) is rather simple:
```js
const client = new Client({
  nodes: ['url1', 'url2', 'url3']
})
```

**Comment by renedx** [comment] 2020-07-05 21:55
> How are you running Elasticsearch? (Docker, executable...)

Executable

> Is Elasticsearch in the same network as the client?

Yes

> Does the user have the permissions to use the nodes API?

Yes

> Providing multiple nodes is rather simple:

Thanks, couldn't find somehow. That will resolve our problem, as the pool request will now succeed.

**Comment by delvedor** [comment] 2020-07-06 05:47
Glad you were able to sort it out!

**Comment by praneeth14** [comment] 2023-05-27 12:16
Hi @delvedor, 
I am able to reproduce this issue and faced this issue in my production service. Even though we give multiple nodes, when sniffing is enabled, the above error will come whenever we onboard a new node to the cluster. Whenever we onboard a new node **_nodes/_all/http** is giving the newly onboarded node details without having **http** info for ~10-15 seconds. 
Because of this ES client tries to update the connection pool every sniffingInterval ms configured, where it will break and my service will be in crash loop because of this. We should check whether **http** is present or not before checking **publish_address** directly.

### Environment
**ES Version:** 7.6.0
**ES Client version:** 7.16.0
**Node Version:** 14.x
**Client Options:**
```
const esClient = new Client({
    nodes: [node1, node2, node2],
    sniffInterval: 5000,
    sniffOnConnectionFault: true,
    maxRetries: 5,
    requestTimeout: 60000
});
```

### Reproducing steps
1. Connect to the existing cluster from the node js client using above-mentioned client options
2. Onboard a new node to the cluster
3. After some seconds the node js client will throw an error and the script will crash

### Expected behavior
The client should skip the node which doesn't have http info by adding a check before directly accessing the publish_address

The newly added node has only this info in the _node/_all/http response (doesn't have http object)
```
{
            "name": "node4",
            "transport_address": "ip:9300",
            "host": "ip",
            "ip": "ip",
            "version": "7.6.0",
            "build_flavor": "default",
            "build_type": "deb",
            "build_hash": "7f634e9f44834fbc12724506cc1da681b0c3b1e3",
            "roles": [
                "ingest",
                "data",
                "ml"
            ],
            "attributes": {
                "ml.machine_memory": "33383047168",
                "ml.max_open_jobs": "20",
                "xpack.installed": "true"
            }
}
```

**Comment by JoshMock** [comment] 2023-08-08 16:09
@praneeth14 I'm now maintaining this client library. Going to reopen this and investigate as I have time. It might be a bit still, but hopefully not 3 more years. :laughing:

**Closed** 2023-08-31 17:21 UTC
Labels: bug, need info, transport
