### ISSUE TITLE
update() method calls the callback before the actual index is done

### ISSUE THREAD

**Issue by ecdeveloper** [elastic/elasticsearch-js#338] opened 2016-01-12 08:07 UTC
When I call update() method, the callback is called almost instantly. But it looks like the data is not indexed yet when the callback is called.

An example doc:
```
{
	field1: value,
	field2: value,
	nestedObjects: [
		{
			obj_id: 1,
			field: value
		},
		{
			obj_id: 2,
			field: value
		}
	]
}
```
The goal is to remove an object by it's id from the nestedObjects array.

Here is the actual script:
```javascript
nestedObj = {};
nestedObj.script_file = 'removeObj';
nestedObj.lang = 'groovy';
nestedObj.params = {
	"obj_id": <some_certain_id>
};

esClient.update({ index: 'users', type: 'user', id: <certain_user_id>, retryOnConflict: 99, body: nestedObj}, cb);
```

Here is the removeObj.groovy, which takes care of deleting the nested object from a document:
```
def item_to_remove = false;
if (ctx._source.nestedObjects) {
	for (obj in ctx._source.nestedObjects) {
		if (obj.id == obj_id) {
			item_to_remove = item;
		}
	}
	if (item_to_remove) ctx._source.nestedObjects.remove(item_to_remove);
}
```

If I query for this document inside the callback, the nested object is still there. If I repeat the search query after a second - it's not there.

Is there a way to wait for the data to be completely indexed somehow?

**Comment by spalger** [comment] 2016-01-12 21:00
I suggest you use `client.get()` rather than `client.search()` inside your callback. As described [in the definitive guide to elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html), elasticsearch is a *near*-realtime search engine, it takes about a second for changes to become searchable. There are ways you can prevent this from being the case (like passing the `refresh` param, or using the `refresh` api), but the near-realtime behavior is there for a reason and bypassing it is not recommended.

Instead, if you do a `client.get()` request the document doesn't have to be searched for because you point to it by ID. In that case you can get a copy of the updated document immediately.

---

However you plan to handle this, it is an elasticsearch behavior and not a bug in the client so I'm going to close the issue

**Closed by spalger** 2016-01-12 21:00 UTC

**Comment by ecdeveloper** [comment] 2016-01-12 21:51
Thanks @spalger, makes a lot of sense. It also seems to be related to this issue - https://github.com/elastic/elasticsearch/issues/1063

**Comment by spalger** [comment] 2016-01-12 21:58
yes
