### ISSUE TITLE
Fields of client.search not returned

### ISSUE THREAD

**Issue by DanielTWalther** [elastic/elasticsearch-js#457] opened 2016-10-28 09:34 UTC
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/12.0/api-reference-2-4.html#api-search-2-4
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/12.0/api-reference.html#api-search

Name of parameter property changed (fields to storedFields); results not as expected:

Old query:

```
client.search({
      'index': indexname,
      'fields': ['name', 'region._id'],
      'body': {
        'filter': {
          'match_all': {}
        }
      }
    }, function (error, response) {
  // ...
});
```

Old result (snippet): 

```
[{ _index: 'el-station',
  _type: 'station',
  _id: '40855',
  _score: 1,
  fields: { name: [ 'München/Hotel' ], 'region._id': [ 903 ] } },
 // ...
]
```

New query:

```
client.search({
      'index': indexname,
      'storedFields': ['name', 'region._id'],
      'body': {
        'filter': {
          'match_all': {}
        }
      }
    }, function (error, response) {
  // ...
});
```

**Expected** new result (snippet):

```
[{ _index: 'el-station',
  _type: 'station',
  _id: '40855',
  _score: 1,
  _source:
   { 
     // ...
     region:
      { _id: 903,
        // ...
        stations: [Object] },
     // ...
     name: 'München/Hotel',
     _id: '40855' },
  fields: { name: [ 'München/Hotel' ], 'region._id': [ 903 ] } },
 // ...
]
```

**Actual** new result (snippet):    (**no** `fields`...)

```
[{ _index: 'el-station',
  _type: 'station',
  _id: '40855',
  _score: 1,
  _source:
   { 
     // ...
     region:
      { _id: 903,
        // ...
        stations: [Object] },
     // ...
     name: 'München/Hotel',
     _id: '40855' } },
 // ...
]
```

**Comment by spalger** [comment] 2016-10-28 18:05
Can you try `docvalueFields`? Also, if you turn on trace logging you will see the requests that the client is actually sending, which I expect would show that you're experiencing an elasticsearch "behavior" or bug

**Comment by DanielTWalther** [comment] 2016-10-31 10:51
New query:

client.search({
      'index': indexname,
      'docvalueFields': ['name', 'region._id'],
      'body': {
        'filter': {
          'match_all': {}
        }
      }
    }, function (error, response) {
  // ...
});

**Comment by DanielTWalther** [comment] 2016-10-31 11:38
Query: 
```
client.search({
      'index': indexname,
      'docvalueFields': ['name', 'region._id'],
      'body': {
        'filter': {
          'match_all': {}
        }
      }
    }, function (error, response) {
  // ...
});
```

Result:
```
[{ _index: 'el-station',
  _type: 'station',
  _id: '40855',
  _score: 1,
  _source:
   { 
     // ...
     region:
      { _id: 903,
        // ...
        stations: [Object] },
     // ...
     name: 'München/Hotel',
     _id: '40855' } },
 // ...
]
```

"Trace":
```
Elasticsearch DEBUG: 2016-10-31T11:26:18Z
  starting request {
    "method": "POST",
    "path": "/el-station/_search",
    "body": {
      "filter": {
        "match_all": {}
      }
    },
    "query": {
      "docvalue_fields": "name,region._id",
      "size": 10000
    }
  }
```

**Comment by DanielTWalther** [comment] 2016-10-31 11:59
"Trace" of API 5.0 `storedFields`:
```
Elasticsearch DEBUG: 2016-10-31T11:52:14Z
  starting request {
    "method": "POST",
    "path": "/csi_rac-station/_search",
    "body": {
      "filter": {
        "match_all": {}
      }
    },
    "query": {
      "stored_fields": "name,region._id",
      "size": 10000
    }
 }
```

"Trace" of API 2.4 `fields`:
```
Elasticsearch DEBUG: 2016-10-31T11:47:22Z               
  starting request { method: 'POST',                    
    path: '/csi_rac-station/_search',                   
    body: { filter: { match_all: {} } },                
    query: { fields: 'name,region._id', size: 10000 } }
```

**Comment by spalger** [comment] 2016-11-01 18:27
Looks like the client is doing the right thing here. I suggest try the [elasticsearch community forums](https://discuss.elastic.co/c/elasticsearch) as this seems to be an issue with the way that elasticsearch is interpreting the request.

**Comment by DominicBoettger** [comment] 2016-11-01 20:11
I am pretty sure you think the client is doing the correct stuff here ;-). Version 11.0.1 works. 12.0 not. So i am pretty sure there were changes which causes this behaviour. It's also reproducable with newer elasticsearch versions on different servers with the same data (recreated indexes).

**Comment by spalger** [comment] 2016-11-05 04:07
I must be missing something, https://github.com/elastic/elasticsearch-js/issues/463 is saying something similar... I'll look into this again

**Comment by DominicBoettger** [comment] 2016-11-18 17:26
Hi @spalger did you find something?
Tried today to use 11.0.1 with ES5 and realized that ES5 compatibility seems to be the main improvement of this version :-).
Should we skip using fields?

Thanks a lot
Dominic

**Comment by spalger** [comment] 2016-11-18 17:34
@DominicBoettger Sorry I don't have a better answer. Are you also trying to use storedFields? Have you tried source filtering?

Consider the warning at the top of this page: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-request-stored-fields.html

**Comment by DominicBoettger** [comment] 2016-11-18 17:38
Tried different stuff, like the old fields and docValueFields.....
I did not use storedFields

**Comment by spalger** [comment] 2016-11-18 17:41
Are you trying to get the values out that you put in? Or the values that elasticsearch has indexed (the analyzed values)?

**Comment by DominicBoettger** [comment] 2016-11-18 17:47
I try to get the values of the object i indexed, not any analyzed fields or something like that.

**Comment by spalger** [comment] 2016-11-18 17:59
Cool, then I suggest switching to source filtering:

```js
client.search({
  filterPaths: [ 'user.*' ]
}).then(resp => {
  console.log(resp.hits.hits[0]._source.user.name);
})
```

**Comment by esamudio** [comment] 2016-12-01 09:10
Hi @spalger,
I was wondering if support for storedFields will be added/approximate timeline for it. Performance is much better when dealing with fields than source (at least before version 5). 

Thanks for all the help! I really appreciate all the hard work you guys put into the elastic products.

**Comment by spalger** [comment] 2016-12-01 16:04
@esamudio stored fields should be supported just fine, they do need to be turned on in your mappings

**Comment by spalger** [comment] 2016-12-02 16:44
Closing this based on #463

**Closed by spalger** 2016-12-02 16:44 UTC
