### ISSUE TITLE
Failed to run on Angular 6: ERROR ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Son-Lam** [elastic/elasticsearch-js#669] opened 2018-05-24 18:06 UTC
**Environment Information**

OS [e.g. Mac, Arch, Windows 10]: OSX 10.13.4
Node Version [e.g. 8.2.1]: 10.1.0
NPM Version [e.g. 5.4.2]: 5.6.0

**Steps to Reproduce**
I attached here a short Angular 6 project. Here is the instruction how to re-produce the issue:
[poc-elasticsearch.zip](https://github.com/elastic/elasticsearch-js/files/2036565/poc-elasticsearch.zip)

1. Install NodeJs 10.1.0
2. Install Angular CLI by running: npm install -g
3. extract the attached zip file
4. cd poc-elasticsearch
5. npm install
6. ng serve --open

**You will get this log in Chrome console:**

```
ERROR ReferenceError: process is not defined
    at Log.push../node_modules/elasticsearch/src/lib/log.js.Log.addOutput (log.js:213)
    at new Log (log.js:51)
    at new Transport (transport.js:19)
    at new EsApiClient (client.js:58)
    at new Client (client.js:101)
    at ElasticSearchService.push../src/app/elasticsearch-service.ts.ElasticSearchService._connect (elasticsearch-service.ts:16)
    at new ElasticSearchService (elasticsearch-service.ts:11)
    at _createClass (core.js:9260)
    at _createProviderInstance$1 (core.js:9234)
    at resolveNgModuleDep (core.js:9200)
```

**Comment by spalger** [comment] 2018-05-24 18:11
Duplicate of https://github.com/elastic/elasticsearch-js/issues/663

**Closed by spalger** 2018-05-24 18:11 UTC
