### ISSUE TITLE
socket hang up error on high volume transactions..

### ISSUE THREAD

**Issue by sahas-** [elastic/elasticsearch-js#521] opened 2017-03-30 02:38 UTC
Hello team,

Version: 12.1.1

I commented this on issue #226 too.. wondering if we can get more guidance on this error 'socket hang up'. My usage is not very high volume, about ~500 requests/sec.. my elasticsearch cluster seems to be healthy ( ie. <10% CPU usage, disk i/o 128KB/s etc), however, on the client side, I keep getting socket hang up on both _search & _update calls.
Provided the log in #226 .
Below is one more specifically to _update call

Elasticsearch ERROR: 2017-03-30T01:43:15Z
  Error: Request error, retrying
  POST http://${myelasticsearch.domain.com}/elasticsearch/${index}/${type}/${doc}/_update => **socket hang up**
      at Log.error (/Users/sahaswaranamam/../node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/sahaswaranamam/../node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/sahaswaranamam/../node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/sahaswaranamam/../node_modules/lodash/lodash.js:4968:19)
      at emitOne (events.js:78:13)
      at ClientRequest.emit (events.js:170:7)
      at Socket.socketOnEnd (_http_client.js:295:9)
      at emitNone (events.js:73:20)
      at Socket.emit (events.js:167:7)
      at endReadableNT (_stream_readable.js:906:12)

Appreciate any guidance to deal with this. 
Thanks in advance.

**Comment by spalger** [comment] 2017-03-30 20:37
Can you try out v13.0.0-beta2? See https://github.com/elastic/elasticsearch-js/issues/476

**Comment by kareljuricka** [comment] 2017-06-09 07:27
Same problem here. What I am trying to do is reindex large data. 

Everytime after **30s** I got Error: **Request Timeout after 30000ms error.**

 If I raise up requestTimeout connection parametr, instead of request timeout error I got after same **30s**:

**Error: Request error, retrying POST http://localhost:9200/_reindex => socket hang up**

When I run reindex with CURL direct request to elasticsearch  (without elasticsearch-js), it works all right.

**Comment by godber** [comment] 2017-06-13 22:19
We have been seeing this issue too.  We experience conditions that can result in bulk requests taking a very long time to run (45 min), and we see these socket errors on these bulk requests.  I can reproduce this scenario in our environment and have been experimenting for the last week or so.

At this point, I have longer bulk requests in a test client working properly if I extend the `requestTimeout` to a really long time and set `keepAlive: false`.

```javascript
...
var client = new elasticsearch.Client({
    host: eshost,
    requestTimeout: 1000 * 60 * 60,
    keepAlive: false,
    log: 'debug',
});
...
```

Right now I am looking into the source of the trouble being the default for the `timeout` option on the `agentkeepalive` package, which according to [its docs](https://github.com/node-modules/agentkeepalive#new-agentoptions) is:

> timeout: {Number} Sets the working socket to timeout after timeout milliseconds of inactivity on the working socket. Default is freeSocketKeepAliveTimeout * 2

I am not sure of this at this point.  But I am sure that disabling `keepAlive` results in a bulk insert that completes correctly without error.

**Comment by godber** [comment] 2017-06-13 22:37
I think it's this `timeout`.  My client will work properly without error even if I leave `keepAlive` enabled and keep my long `requestTimeout`, but then also modify `makeAgentConfig` in `lib/connectors/http.js` so that it sets `timeout` to something large, somewhat like this:

```
HttpConnector.prototype.makeAgentConfig = function (config) {
  var agentConfig = {
    keepAlive: config.keepAlive,
    keepAliveMsecs: config.keepAliveInterval,
    maxSockets: config.maxSockets,
    maxFreeSockets: config.keepAliveMaxFreeSockets,
    freeSocketKeepAliveTimeout: config.keepAliveFreeSocketTimeout,
    timeout: 1000 * 60 * 60
  };

  if (this.useSsl) {
    _.merge(agentConfig, this.host.ssl);
  }

  return agentConfig;
};
```

Perhaps the `timeout` value used by `agentkeepalive` should be the same as `requestTimeout` ... those are conceptually the same thing right?

**Comment by spalger** [comment] 2017-06-14 23:06
Interesting point @godber, I'm hesitant to base the timeout in `agentkeepalive` on the `requestTimeout` config because that value can technically be set per request...

I wonder what the drawbacks of disabling `agentkeepalive`'s timeout and instead relying on our own timeouts would be...

**Comment by godber** [comment] 2017-06-15 19:50
@spalger I don't have a good understanding of the overall architecture of `elasticsearch-js`, but couldn't you do it the other way around?  That is, just rely on the `agentkeepalive` timeout and handle the timeout error if it throws it, using that to trigger your retries?  Are there other reasons you're forced to handle timeouts on your own?

I guess you could add another configuration parameter that sets the `agentkeepalive` timeout, but it feels like they are serving the same role.

**Comment by hathija** [comment] 2017-06-30 06:50
Hello,

i'm getting the same issue as @sahas- while migration ES (2.4 to 5.4) and nodejs pckage (12.0 to 13.0).
How did you resolve? Thanks

**Comment by tiste** [comment] 2017-07-07 07:43
Hello,

Same as @hathija, we've upgraded from 2.4 to 5.4, lib as well, and while doing bulk requests (around 100mb), the socket hang up.
Will try to put `keepAlive` to `false`.

Thanks for your help.

**Comment by helmutkian** [comment] 2017-07-12 18:19
Experiencing the same issue. Anyone have a work around?

**Comment by calvinwiebe** [comment] 2017-07-12 19:16
@spalger I thought I'd take a closer look into this. Since there have been enough reports in this issue, and #508, to suggest that this is a real problem. It hasn't gotten much attention, and has been open for 3 months :(. 

Regarding the timeouts, as far as I can see, `elasticsearch-js` has [agentkeepalive: ^2.2.0](https://github.com/elastic/elasticsearch-js/blob/master/package.json#L101) in its package.json. In that version, the option for the _free socket timeout_ is [keepAliveTimeout](https://github.com/node-modules/agentkeepalive/blob/2a913cc13a5802283693577f46284247c3108aa2/lib/_http_agent.js#L64). However, `elasticsearch-js` is passing in [freeSocketKeepAliveTimeout](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/connectors/http.js#L97). That latter option name is what is used in [agentkeepalive >= 3.x](https://github.com/node-modules/agentkeepalive/blob/master/lib/_http_agent.js#L68). Therefore, as it stands, `agentkeepalive` will be locked to its default timeouts for both the _free_ and _active_ sockets (15s and 30s, respectively). I hacked up my locally installed `agentkeepalive` to log out the option values to make sure I wasn't jumping to conclusions and being blind, and what I described seems to be the case. (I'm guessing this might have happened because the initial addition of the `agentkeepalive` happened 8 months ago, but the adding of the options inside `elasticsearch-js` happened 3 months ago, which was after the option/documentation rename in `agentkeepalive`). 

```
OPTIONS GIVEN BY elasticsearch
{ keepAlive: true,
  keepAliveMsecs: 1000,
  maxSockets: Infinity,
  maxFreeSockets: 256,
  freeSocketKeepAliveTimeout: 60000 }
OPTIONS DEFAULTED BY agentkeepalive
{ keepAlive: true,
  keepAliveMsecs: 1000,
  maxSockets: Infinity,
  maxFreeSockets: 256,
  freeSocketKeepAliveTimeout: 60000,
  keepAliveTimeout: 15000,
  timeout: 30000 }
```

It makes sense that `keepAlive: false` is working for those above, since we bypass the `agentkeepalive` library completely. We then loose the performance benefits it should provide, though. 

If this is fixed, then at least the _active socket_ timeout will be [double](https://github.com/node-modules/agentkeepalive/blob/master/lib/agent.js#L31) the `freeSocketKeepAliveTimeout`, so users of this library can control that somewhat. However, I think it would be a good idea to expose a `activeSocketKeepAliveTimeout`, as @godber  suggested above, to override the `agentkeepalive` `timeout` option. Especially since the default of [net.Socket](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) is to have _no_ timeout.


If this is indeed the problem, I could work on a PR if your schedule is packed. However, this is a pretty fundamental change and would prefer the owner to take a crack at it :).

**Comment by imyoungyang** [comment] 2017-07-17 01:35
Hi

I encountered the same error message but in the "cluster" mode. I used version 13.2.0 client to connect elastic 5.5.0. But interested thing is that I did not encountered this issue if I connected to single node.

`Elasticsearch ERROR: 2017-07-14T11:19:09Z
  Error: Request error, retrying
  POST http://localhost:9200/products/goodsListInCate/_bulk => socket hang up
      at Log.error (/Users/youngbe/Dev/ehs-new-gitlab/iceCream/nodeTools/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/youngbe/Dev/ehs-new-gitlab/iceCream/nodeTools/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/Users/youngbe/Dev/ehs-new-gitlab/iceCream/nodeTools/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/Users/youngbe/Dev/ehs-new-gitlab/iceCream/nodeTools/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketCloseListener (_http_client.js:285:9)
      at emitOne (events.js:101:20)
      at Socket.emit (events.js:188:7)
      at TCP._handle.close [as _onclose] (net.js:501:12)`

**Comment by goravsingal** [comment] 2017-07-17 09:40
I found that, if I use "http-aws-es" lib to connect via aws auth, it breaks.
If I left my ES instance on aws open to public (just for testing), and leave "http-aws-es" code unused. It works fine.

I ended up using: "aws-es" npm lib.

**Comment by rhughes89** [comment] 2017-07-24 15:16
This problem seems to be haunting me as well. No matter what settings I change, it will "seemingly"  fixes the problem but it always comes back. I tried even minimizing the size of the bulk operation but nothing seems to be a permanent fix.

It's getting to the point where if it fails to bulk index into elastic search, I catch the error and add each one one by one. That I have never had the problem on indexing a single record.

**Comment by mfeltscher** [comment] 2017-08-09 20:29
I encountered the same issue using `13.2.0` and Elasticsearch `5.5.1`. From what I can see I think @calvinwiebe's assumption is correct and this should be fixed (as described in #582). For me this issue is `13.x` related since I never encountered it using `12.x`.

**Comment by ynux** [comment] 2017-09-17 10:10
Same issue, with elasticsearch 5.6.0 in elastic cloud, pushing data with nodejs v8.2.1 and elasticsearch client 13.0.0-rc2

**Comment by k0t0fey** [comment] 2017-10-10 23:02
Same issue with elasticsearch 5.6.2 and elasticsearch client 13.3.1

**Comment by acarstoiu** [comment] 2017-10-27 10:41
This issue was reported **7 months** ago and it still wastes people's time. There are in fact two bugs:
- the blocking one, identified by @godber and caused by a narrow-sighted decision in `agentkeepalive` to set a timeout on sockets, if none was specified; but in the case of `elasticsearch-js` the `requestTimeout` parameter **must always prevail**
- the less severe one, discovered by @calvinwiebe, which is a name confusion for the parameter that sets the time for which free sockets are kept around

All you need to do is this:
```lang=patch
--- src/lib/connectors/http.js	2017-08-09 06:11:25.000000000 +0000
+++ src/lib/connectors/http.js	2017-10-27 09:04:53.756157518 +0000
@@ -93,7 +93,8 @@
     keepAliveMsecs: config.keepAliveInterval,
     maxSockets: config.maxSockets,
     maxFreeSockets: config.keepAliveMaxFreeSockets,
-    freeSocketKeepAliveTimeout: config.keepAliveFreeSocketTimeout
+    keepAliveTimeout: config.keepAliveFreeSocketTimeout,
+    timeout: 0
   };
 
   if (this.useSsl) {
```
Consider it a pull request.

**Comment by executives** [comment] 2017-11-08 21:25
I've been running into the same issue.

[This thread](https://github.com/elastic/elasticsearch-js/issues/508) mentions using the **beta** version of elasticsearch.js

`npm install elasticsearch@beta`

Using the above command, I was able to bulk add 100k records with no errors.

I recommend giving this a try.

**Comment by hangang128** [comment] 2018-01-25 20:43
Got the same issue. The patch and @beta didn't work. It turned out that our app is submitting ~200 request at the same time(looping in node.js :( ). I have to stagger the requests with q.delay(variable time) to avoid time out.

**Comment by spalger** [comment] 2018-01-31 19:01
Fixed in #600

**Closed by spalger** 2018-01-31 19:01 UTC
Labels: :networking, feedback needed

**Comment by Faizanq** [comment] 2018-10-10 11:12
Hi @godber I try your solution but still am facing timeout issue

**Comment by senthilbalajiganesan** [comment] 2018-12-26 06:06
you can set requestTimeout to Infinity while creating connection instance
