### ISSUE TITLE
Incorrect TypeScript typings for `function_score`

### ISSUE THREAD

**Issue by arslivinski** [elastic/elasticsearch-js#2255] opened 2024-05-09 22:13 UTC
## 🐛 Bug Report

[According to the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random), I should be able to pass a `random_score` to a `function_score`. However, the TypeScript type appears to be wrong, not allowing this property.

Note that I'm using this package for the typings only.

## To Reproduce

The following code

```ts
import type { estypes } from "@elastic/elasticsearch";

export const request: estypes.SearchRequest = {
  query: {
    function_score: {
      random_score: {
        seed: 10,
        field: "_seq_no",
      },
    },
  },
};
```

Results in this error

```
Object literal may only specify known properties, and 'random_score' does not exist in type 'QueryDslFunctionScoreQuery'.
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nFBnJrtwC+cAZlBCHAEQACKANgIa7ADGA9A8zG9io1FYALKgG4AUOJQAPSLDisIAO1xwoKAI4BXHDABcWXMhwA6AMr9BQgEqadqgLwZxcONpRREB9C9ektSqw8ygD62Irq3r5+aoxKACYUYREoUTExfCjxBgCMAAwANNHpJMAM2dRhmiFKEFRF6UQNfoTNreKEEkA)

## Expected behavior

No error.

## Your Environment

- *node version*: 18.20.0
- `@elastic/elasticsearch` *version*: >=8.12.2
- *os*: Ubuntu 22.04.4

**Comment by JoshMock** [comment] 2024-05-14 16:51
Duplicate of https://github.com/elastic/elasticsearch-specification/issues/2109, but I'll keep it open here so you get notified when that gets fixed. It's been sitting for a bit, but hopefully I can circle back to it soon. :upside_down_face:

**Comment by JoshMock** [comment] 2024-08-29 17:03
A fix has been provided in https://github.com/elastic/elasticsearch-specification/pull/2833. Closing this, please follow that PR for updates.

**Comment by JoshMock** [comment] 2024-09-03 19:18
A fix is in https://github.com/elastic/elasticsearch-specification/pull/2852.

**Comment by JoshMock** [comment] 2024-09-30 18:03
Closing without fixing. [Full context here](https://github.com/elastic/elasticsearch-specification/pull/2852#issuecomment-2383564729) as to why we won't be fixing this right now.

**Closed by JoshMock** 2024-09-30 18:03 UTC
Labels: Area: Specification, Category: Bug
