### ISSUE TITLE
Stable version of node (v4.0.0) failure to create client

### ISSUE THREAD

**Issue by peterwillis** [elastic/elasticsearch-js#269] opened 2015-09-11 09:26 UTC
```javascript
new elasticsearch.Client({
  host: 'http://localhost:9200'
});
```

Fails with error:

```shell
RangeError: Maximum call stack size exceeded
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:65:40)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
   at Log.listenerCount (/Users/pete/Projects/bbg/node_modules/elasticsearch/src/lib/log.js:68:25)
   at Function.EventEmitter.listenerCount (events.js:399:20)
```

This happens on the first call to ```log.info``` in connection_pool.js line 276:

```javascript
this.log.info('Adding connection to', connection.id);
```

**Comment by spalger** [comment] 2015-09-11 19:06
Duplicate of https://github.com/elastic/elasticsearch-js/issues/265

**Closed by spalger** 2015-09-11 19:06 UTC
