### ISSUE TITLE
Not working with Proxy - should not add a leading slash to path (host.js)

### ISSUE THREAD

**Issue by ryan65** [elastic/elasticsearch-js#402] opened 2016-05-17 06:14 UTC
Hi 
I am working behind a proxy and I have an elastic search service up in aws
var client = new elasticsearch.Client({
  host: {host: myproxy, port: myport, path: AWSEndPoint},
    log: 'trace'

});
I found that my requests do not work  (I get http result 400) 

This is due to the fact that you add a leading slash in host.js to the path (this.path = '/' + (this.path || ''))
**if I remove this line and do not modify the path then everything works** 
1. Why do you need this extra leading slash
2. When can you fix this issue 
Thanks.

**Comment by clakech** [comment] 2016-08-01 13:17
Maybe this code can help someone.

Add an env variable to reach your proxy `HTTP_PROXY = http://127.0.0.1:5000/`

```javascript
const elasticsearch = require('elasticsearch');
const proxy = require('proxy-agent');

const client = new elasticsearch.Client({
  host: 'my.host.com',
  createNodeAgent: () => proxy(process.env.HTTP_PROXY)
);

client.search(query);
```

Au revoir :kissing_closed_eyes:

**Comment by spalger** [comment] 2017-04-07 17:12
Duplicate of https://github.com/elastic/elasticsearch-js/issues/101

**Closed by spalger** 2017-04-07 17:12 UTC
