### ISSUE TITLE
Cannot create a Transport with request in typescript

### ISSUE THREAD

**Issue by jonnymwright** [elastic/elasticsearch-js#886] opened 2019-06-24 14:00 UTC
## 🐛 Bug Report

`Transport.request` has two overloads and these have different return types. In addition the overload with the extra parameter (`request(params, options, callback)`) defines the third parameter as optional. This means that the type system cannot determine which of the methods is being overridden, and gets confused with the return type.

## To Reproduce

```ts
class MyTransport extends Transport {
  public request(
    params: TransportRequestParams,
    options?: TransportRequestOptions,
    callback?: (err: Error | null, result: ApiResponse) => void)
  : TransportRequestCallback
  {
    // some of the worlds most awesome code ...
    const result = super.request(params, options, callback)
    return result
  }
}
```

## Expected behavior

Code compiles without error

## Actual behaviour

```
Property 'request' in type 'MyTransport' is not assignable to the same property in base type 'Transport'.

Type '(
  params: TransportRequestParams, 
  options?: TransportRequestOptions | undefined, 
  callback?: ((err: Error | null, result: ApiResponse<any, any>) => void) | undefined) 
=> TransportRequestCallback' 

is not assignable to type '{ 
(
  params: TransportRequestParams, 
  options?: TransportRequestOptions | undefined
): Promise<ApiResponse<any, any>>;
(
  params: TransportRequestParams, 
  options?: TransportRequestOptions | undefined, 
  callback?: ((err: Error | null, result: ApiResponse<...>) => void) | undefined
): TransportRequestCallback; 
}'.

Type 'TransportRequestCallback' is missing the following properties from type 'Promise<ApiResponse<any, any>>': then, catch, [Symbol.toStringTag], finally
```

Notice the first type that the type system tries to assign is the overload of the method that I am not trying to implement. 

I've tried removing the optional flag from `options`, and `callback`, and also declaring the return type as `TransportRequestCallback | Promise<ApiResponse>`, and had to revert to declaring the return type as `any`

## Your Environment

- *node version*: 6.7.0
- *typescript version*: 3.5.1
- `@elastic/elasticsearch` *version*: 7.1.0
- *os*: Windows

**Comment by delvedor** [comment] 2019-07-01 07:11
Hello!
I'm trying to track down this issue.

**Comment by zoellner** [comment] 2020-08-24 10:38
@delvedor is there an update on this? I am running into an issue with a custom Transport and I think that the underlying issue is that it is fundamentally unclear whether the request should be async or have a callback or both (and that question might potentially have a different answer when using the bulk helper). 
I couldn't find proper tests either for using a custom Transport, so it's difficult to expand on that and properly describe my issue.

**Comment by delvedor** [comment] 2020-09-01 10:52
I think it should:
https://github.com/elastic/elasticsearch-js/blob/02ed45f76bc292b60aa2264ebbe56122fd7c61a6/lib/Transport.d.ts#L156-L157

Can you add a snippet of code for reproducing the issue?

**Comment by inneon** [comment] 2020-09-01 11:29
This shows the issue

https://stackblitz.com/edit/typescript-playground-5ab3zc?file=MyTransport.ts

**Comment by delvedor** [comment] 2020-09-01 12:15
Thank you for the snippet @inneon!

It looks like the solution is to override both `Transport.request` definitions :)

```ts
import { Transport, ApiResponse } from '@elastic/elasticsearch'
import {
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestCallback,
  TransportRequestPromise,
} from '@elastic/elasticsearch/lib/Transport'

class MyTransport extends Transport {
  public request(
    params: TransportRequestParams,
    options?: TransportRequestOptions
  ): TransportRequestPromise<ApiResponse>
  public request(
    params: TransportRequestParams,
    options?: TransportRequestOptions,
    callback?: (err: Error | null, result: ApiResponse) => void)
  : TransportRequestCallback
  {
    // some of the worlds most awesome code ...
    const result = super.request(params, options, callback)
    return result
  }
}
```

I'm closing the issue as it seems to be resolved, feel free to reopen if you think there is still something to fix!

**Closed by delvedor** 2020-09-01 12:15 UTC
Labels: bug, typescript

**Comment by zoellner** [comment] 2020-09-01 12:29
I'm not typescript expert but I don't think this works in js. the second request class member would simply overwrite the first one

**Comment by delvedor** [comment] 2020-09-01 12:30
The code above is typescript, there is no *overload* concept in js.

**Comment by zoellner** [comment] 2020-09-01 12:31
What I'm trying to say is that in js it doesn't seem to make sense to "override both" definitions since there is only one class member named "request" anyways

**Comment by delvedor** [comment] 2020-09-01 12:35
In js there are no definitions ;)

If you need to override the code and you are using javascript:
```js
class MyTransport extends Transport {
  request (params, options, callback) {
    // handle both callback and promises
  }
}
```

If you are using typescript: 
```ts
class MyTransport extends Transport {
  public request(
    params: TransportRequestParams,
    options?: TransportRequestOptions
  ): TransportRequestPromise<ApiResponse>
  public request(
    params: TransportRequestParams,
    options?: TransportRequestOptions,
    callback?: (err: Error | null, result: ApiResponse) => void)
  : TransportRequestCallback
  {
    // handle both callback and promises
  }
}
```

**Comment by zoellner** [comment] 2020-09-01 13:25
ok, this might be too far from the original issue, so let me know if I should create  new one but here's some code to demonstrate the issue:
https://gist.github.com/zoellner/02cf2f53a6d0277ea47d91a4825a0ccb

The only requirement I have is to await one promise in the request of the custom transport. I've implemented two variations. One is more async style, the other one callback style. 

You can see that everything works fine for "normal" requests using either of the custom transports but both lead to an UnhandledPromiseRejectionWarning with the bulk helpers.

**Comment by delvedor** [comment] 2020-09-01 15:21
The `Transport.request` implementation **must** use callbacks.

**Comment by zoellner** [comment] 2020-09-01 17:57
both of these implementations do use callbacks. they just happen to return a promise as well.
