### ISSUE TITLE
ProductNotSupportedError: The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by liukaigsx** [elastic/elasticsearch-js#1520] opened 2021-08-14 03:54 UTC
## 💬 Questions and Help

`/usr/lib/node_modules/@elastic/elasticsearch/lib/Transport.js:460
            const err = error || new ProductNotSupportedError(result)
                                 ^

ProductNotSupportedError: The client noticed that the server is not a supported distribution of Elasticsearch
    at EventEmitter.<anonymous> (/usr/lib/node_modules/@elastic/elasticsearch/lib/Transport.js:460:34)
    at Object.onceWrapper (node:events:514:26)
    at EventEmitter.emit (node:events:394:28)
    at /usr/lib/node_modules/@elastic/elasticsearch/lib/Transport.js:590:40
    at onBody (/usr/lib/node_modules/@elastic/elasticsearch/lib/Transport.js:358:9)
    at IncomingMessage.onEnd (/usr/lib/node_modules/@elastic/elasticsearch/lib/Transport.js:275:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  meta: {
    body: null,
    statusCode: null,
    headers: null,
    meta: {
      context: null,
      request: { params: null, options: null, id: 1 },
      name: 'elasticsearch-js',
      connection: null,
      attempts: 0,
      aborted: false
    }
  }
}
`

**Comment by jagadeesh93** [comment] 2021-08-14 15:57
Same for me @delvedor

**Comment by RTodorov** [comment] 2021-08-14 17:12
Duplicate of #1519

**Closed** 2021-08-15 01:15 UTC
