### ISSUE TITLE
TypeScript Definition 

### ISSUE THREAD

**Issue by sdnetwork** [elastic/elasticsearch-js#294] opened 2015-11-09 15:08 UTC
it could be good to have a TypeScript Definition (.d.ts) for this library it is very useful to use with atom.io and others ide.

do you know if this is scheduled ?

**Comment by spalger** [comment] 2015-11-09 15:09
duplicate of https://github.com/elastic/elasticsearch-js/issues/59

**Closed by spalger** 2015-11-09 15:09 UTC
